### ISSUE TITLE
微信小程序，多个canvas如何设置？

### ISSUE THREAD

**Issue by zhwy** [deepkolos/three-platformize#10]
> platform = new WechatPlatform(canvas);
> THREE.PLATFORM.set(platform);

THREE.PLATFORM只能绑定一个？这样我多个canvas就没法同时绘图了。

在不同的页面中绘图，每个页面中都会调用THREE.PLATFORM.set(platform)，会出现以下问题：

![image](https://user-images.githubusercontent.com/16789591/113247080-d5182a80-92ec-11eb-8d4d-c4e7ac493b9c.png)

**Comment by deepkolos** [comment]
还没考虑到这种情况

如果canvas布局上面没有什么特殊，可以通过裁剪，控制绘制区域，不同区域使用不同场景和相机绘制？

**Comment by deepkolos** [comment]
增加了多个页面公用一个three-platform的构建配置和例子

https://github.com/deepkolos/three-platformize-demo-wechat

测试的页面跳转路径是

pages/empty/index -> pages/index/index -> pages/empty/index -> pages/index-copy/index-copy

**Comment by zhwy** [comment]
不好意思，回复晚了。我是在轮播中使用，每个轮播图片是一个canvas，展示一个模型。

原本我是通过THREE.PLATFORM.dispose()先释放上一个展示内容，再重新set下一个的canvas，这样不会报错。

有公用的就方便多了，感谢！

**Comment by deepkolos** [comment]
这种的话，估计建议还是一个canvas吧，模型切换类似五福那个，ios下webgl内存释放不干净没打开页面没几次估计小程序就内存不足或者微信直接崩掉
