### ISSUE TITLE
关于淘宝小程序渲染threejs

### ISSUE THREAD

**Issue by xiaoFeng5210** [deepkolos/three-platformize#11]
作者你好，作为一个开发者 目前正在着手准备在淘宝小程序中使用threejs,目前需要渲染的模型格式主要为 gltf格式以及dae格式。。。所以 现在 这个框架可以在生产中使用了吗～？目前还是担心出现很多未知问题

**Comment by deepkolos** [comment]
真机确实很多问题，淘宝小程序的话，暂时不太建议生成环境下使用，可以自己先拿来调研

**Comment by xiaoFeng5210** [comment]
感谢回复～，目前准备调研渲染一些简单模型。。。

**Comment by deepkolos** [comment]
目前taobao demo glb 可以正常显示了，其他loader 因为域名限制真机无法展示，可用云存储放模型文件
