### ISSUE TITLE
请问如何使用OrbitControls？

### ISSUE THREAD

**Issue by jenerse** [deepkolos/three-platformize#12]
OrbitControls 是在哪个包导入？

**Comment by deepkolos** [comment]
可以参考这个DEMO仓库，里面很有例子

https://github.com/deepkolos/three-platformize-demo-wechat

![demo](https://user-images.githubusercontent.com/12824616/114653368-7a35f880-9d1a-11eb-9f9b-853903a10f6f.gif)
