### ISSUE TITLE
canvas渲染成功后，卸载，会出现残留，没办法释放干净

### ISSUE THREAD

**Issue by pxim** [deepkolos/three-platformize#13]
首次渲染结果：
![image](https://user-images.githubusercontent.com/5111701/114648230-11964e00-9d11-11eb-8b76-a53eb5423dab.png)

react组件卸载，删除canvas后，再次添加canvas组件后结果；
![image](https://user-images.githubusercontent.com/5111701/114648414-5326f900-9d11-11eb-85be-2a0b8dd9067b.png)

我把微信调试工具里元素都设置 display=none了，渲染的mesh还在界面上，请问是内部哪个元素呈现画面的，怎么清理释放掉；我把我的canvas也隐藏了，也没用
![image](https://user-images.githubusercontent.com/5111701/114651651-f62e4180-9d16-11eb-8142-8671f1d9e943.png)

![image](https://user-images.githubusercontent.com/5111701/114648556-a436ed00-9d11-11eb-98ee-8a173f0c8e83.png)
![image](https://user-images.githubusercontent.com/5111701/114648516-93867700-9d11-11eb-81ea-098619bc7600.png)

**Comment by deepkolos** [comment]
还没使用过taro来编写小程序

关于模拟器上面是有问题的，模拟器上的canvas不能被裁剪，总是在最上面，可以真机上试试，关于清除webgl画面可以使用一下API

```js
renderer.clear( true, true, true );
```

关于内存释放的测试可以参考这个仓库

https://github.com/deepkolos/three-platformize-demo

https://github.com/deepkolos/three-platformize-demo-wechat

![demo](https://user-images.githubusercontent.com/12824616/114653368-7a35f880-9d1a-11eb-9f9b-853903a10f6f.gif)

**Comment by pxim** [comment]
> ```js
> renderer.clear( true, true, true );
> ```

卸载的时候用下 renderer.clear( true, true, true ); 就没问题了，谢谢了
