### ISSUE TITLE
基于微信小程序开发的问题

### ISSUE THREAD

**Issue by GoodGoodStudy12138** [deepkolos/three-platformize#14]
你好，作者。我在一个推送上看到了这篇文章，觉得特别好，但是对于微信小程序端的使用我还是不太了解。新增调用后，一直有报错，能否出一期微信小程序开发的过程，直接导入开发工具进行学习，不胜感激。

**Comment by deepkolos** [comment]
如果熟悉rollup的话，可以先看看这两个仓库的代码

https://github.com/deepkolos/three-platformize-demo
https://github.com/deepkolos/three-platformize-demo-wechat

我周末新增个最简单的demo吧，目前的demo主要是测试用例，为了跨小程序，又抽离了一层，所以不熟悉构建的同学可能就比较迷惑了

**Comment by GoodGoodStudy12138** [comment]
好哒，谢谢大佬赐教

**Comment by deepkolos** [comment]
最基础的demo提供

https://github.com/deepkolos/three-platformize-demo-wechat-simple
