### ISSUE TITLE
真机渲染文字问题

### ISSUE THREAD

**Issue by jenerse** [deepkolos/three-platformize#18]
[https://github.com/deepkolos/three-platformize/issues/17](url)
这个issue是上面issue的延伸。ios渲染会导致微信闪退，安卓渲染不出来。
真的神多坑。。
请问作者有实验过可以吗～有的话求指点一下～谢谢～

**Comment by deepkolos** [comment]
适配了fontloader，不过估计不太符合使用场景，svgloader不知道支不支持文字

**Comment by jenerse** [comment]
@deepkolos 找到方法了，先把canvas转成base64，然后用TextureLoader加载就可以。

    const imageData = canvas.toDataURL();
    return new THREE.TextureLoader().load(imageData);

fontloader 看效果好像也可以是2d文字，不知道能不能实现。。有待验证。。

**Comment by deepkolos** [comment]
fontloader加载是3d的文字

**Comment by jenerse** [comment]
搞了一大圈
