### ISSUE TITLE
VideoTexture 微信小程序上支持吗？

### ISSUE THREAD

**Issue by wujianv5** [deepkolos/three-platformize#19]
VideoTexture 需要 video，但微信小程序的video不是原生的video，有什么办法支持 VideoTexture 吗？

**Comment by deepkolos** [comment]
video可以画在canvas上，然后requestAnimationFrame从canvas读出来

**Comment by deepkolos** [comment]
另一Issue 有解决方法可参考

https://github.com/deepkolos/three-platformize/issues/17
