### ISSUE TITLE
URL.createObjectURL  微信平台的兼容性

### ISSUE THREAD

**Issue by DaskV** [deepkolos/three-platformize#26]
看过源码 发现3DMloader  最终会使用 URL.createObjectURL（Blob） 来生成  rhino3dm.js 的本地路径， 看URL.js 里的 todo说 用wx.fileSystemManager 来做临时路径，不知道搞好了吗？

另外我的项目是用 UniAPP 做的， OrbitControls  却不生效， 不管官方的demo， 还是我自己的模型，都不能使用controls 调整相机的位置

以上都是 wechatPlatform 出现的问题， H5正常

**Comment by deepkolos** [comment]
小程序不支持动态加载js, 这个无法修复的, 只能改绕过, 代码引用

**Comment by WhiteCjy** [comment]
老哥，问题都解决了吗，能请教下吗
