### ISSUE TITLE
微信小程序setMeshoptDecoder must be called before loading compressed files。。

### ISSUE THREAD

**Issue by Frankling** [deepkolos/three-platformize#29]
微信小程序setMeshoptDecoder must be called before loading compressed files。。

import { MeshoptDecoder } from 'three-platformize/examples/jsm/libs/meshopt_decoder.module.js';
import { GLTF, GLTFLoader } from 'three-platformize/examples/jsm/loaders/GLTFLoader'
            const gltfLoader = new GLTFLoader()
            gltfLoader.setMeshoptDecoder(MeshoptDecoder);
这样使用应该是对的把。。

**Comment by deepkolos** [comment]
const gltfLoader = new GLTFLoader()
gltfLoader.setMeshoptDecoder(MeshoptDecoder);

这两行需要在PLATFORM.set 设置后执行
