### ISSUE TITLE
canvasW and extension.MIN_EXT is not defined in TaobaoPlatform

### ISSUE THREAD

**Issue by Oyh** [deepkolos/three-platformize#3]
1. should use `this.canvasH` and  `this.canvasH` in line 67 and 73
2. in real machine test, `extensions.get( 'EXT_blend_minmax' );` will return {}, `extension.MIN_EXT` and `extension.MAX_EXT` will be undefined

**Comment by deepkolos** [comment]
感谢反馈，extensions.get( 'EXT_blend_minmax' )返回的为空的问题貌似反馈到淘系互动的钉钉群了

估计是3个修的方式，一个

1. 是让three认为EXT_blend_minmax扩展不支持
2. 修改extensions.get( 'EXT_blend_minmax' );的返回值，把代码固定替换webview上支持的
3. 等官方修复

**Comment by deepkolos** [comment]
已修复，textureload也正常了
