### ISSUE TITLE
微信小程序无法正确加载gltf模型

### ISSUE THREAD

**Issue by LiuXianBang** [deepkolos/three-platformize#31]
![image](https://user-images.githubusercontent.com/13533545/163665462-7db87d75-eadc-4547-9ce4-ca8468e1b0ef.png)
同样的代码，加载demo自带的RobotExpressive.glb可以正常加载，但是加载我的model.glb时候却无法正常加载，不知道是否是模型大小问题，我的mode.glb文件大概1M大小，模型可以在·Online 3DViewer中正常打开，但在小程序中无法加载也没有别的错误提示。希望能得到帮助

**Comment by 0x3f97** [comment]
遇到了同样的问题，后来有解决吗

**Comment by deepkolos** [comment]
可以检测模型所使用的的纹理分辨率是否超过2048*2048 @382009  @0x3f97

**Comment by LiuXianBang** [comment]
感谢回复，经过研究，应该是模型过大的问题。通过压缩glb模型可以正常加载。
