### ISSUE TITLE
淘宝小程序 真机预览失败

### ISSUE THREAD

**Issue by YouZihui** [deepkolos/three-platformize#4]
使用 uniapp的  hbuilder创建 uniapp项目  运行到支付宝小程序   项目类型选择 淘宝小程序
在开发工具中查看一切正常  app.json 中 enableSkia 设置为true后   预览到手机时会遇到问题
    THREE.$requestAnimationFrame会卡死闪退
		使用canvas.requestAnimationFrame 代替 THREE.$requestAnimationFrame 后
			renderer.render 时  貌似渲染位置不正确
			textureLoader.load 加载图片资源  onload和onerror 都不会走

hbuilderX版本 3.1.2
小程序开发者工具版本 1.17.9
测试手机  小米MIX2S
手机淘宝版本 9.21.1

使用 npm 安装的 three-platformize  然后手动替换为github上的 three-platformize

**Comment by deepkolos** [comment]
支付宝小程序看文档记得是开放支持webgl

**Comment by deepkolos** [comment]
THREE.$requestAnimationFrame 其实就是转发 到 canvas.requestAnimationFrame，可以查看TaobaoPlatform

**Comment by deepkolos** [comment]
淘宝小程序的适配缺少真机测试appid，所以目前只是模拟器上面跑起来了，如果能提供一个就好了

**Comment by YouZihui** [comment]
感谢回复

我试的也是淘宝的小程序  选择项目类型的时候  不是支付宝的   测试用的也是淘宝扫码打开


我也是看了 TaobaoPlatform 的js后 用的 canvas.requestAnimationFrame 代替的 不过真机上看  两个效果确实不一样 一个是感觉卡顿  一两秒后闪退到淘宝app的首页   一个是canvas的位置变换到右下角 （通过添加canvas背景颜色 和修改 top left确认的）


我用的也是别人的淘宝appid  。。

**Comment by deepkolos** [comment]
对了，今天看到支付宝开发了个oasis 3d引擎有适配淘宝小程序的适配器，可以看看是怎么适配的，是一个参考解法

**Comment by deepkolos** [comment]
我这边有账号了，完善后上传

![图片](https://user-images.githubusercontent.com/12824616/109135612-3733bc00-7792-11eb-99c0-2e891fc198ce.png)
