### ISSUE TITLE
微信小游戏开发 轨道控制器（OrbitControls）苹果真机无效

### ISSUE THREAD

**Issue by liujianqiaoa** [deepkolos/three-platformize#45]
微信小游戏开发 轨道控制器（OrbitControls）苹果真机无效

**Comment by deepkolos** [comment]
@liujianqiaoa 后续维护将在 https://github.com/deepkolos/platformize 进行了

**Comment by deepkolos** [comment]
@liujianqiaoa 问题修复了,原因是微信ios 下 wxGame.onTouchMove event.type 是"ontouchmove" 而非 "touchmove" 导致的

https://github.com/deepkolos/platformize/tree/main/examples/three-wechat-game/minigame

**Comment by deepkolos** [comment]
@liujianqiaoa 如果依然使用老项目的话, 可以参考这个commit修复

https://github.com/deepkolos/platformize/commit/047e5c2e78702cc1f4308bfd2f8bd66e050ac51d

**Comment by liujianqiaoa** [comment]
非常感谢，因为ios 真机调试需要ios6才行。身边找不到ios6的适配机型。非常感谢博主修改和提醒
