### ISSUE TITLE
THREE.FileLoader 错误

### ISSUE THREAD

**Issue by wujianv5** [deepkolos/three-platformize#5]
微信小程序模拟器中跑 three-platformize-demo-wechat，点击 GLTFLoader 后程序报错，debug了一下代码，错误发生在 XMLHttpRequest.js 中，如下截图
![image](https://user-images.githubusercontent.com/4354926/108670646-3133a600-751a-11eb-9ab4-b8e3473039cc.png)
data 是 ArrayBuffer 类，但是 data instanceof ArrayBuffer 却返回false。

微信官方的 threejs 兼容库大概也有同样的问题，调用 THREE.FileLoader().load(...) 回调中的数据也是错的。

**Comment by deepkolos** [comment]
我这边用的模拟器是window版的1.05.2101192，倒是没遇到这个问题，如果是windows平台的话，要不反馈下微信开发工具的版本

**Comment by deepkolos** [comment]
我知道了，是微信开发工具版本问题，升级微信开发工具或者把three-platformize-demo-wechat的project.config.json的。。。我忘记了，要不先升级开发工具吧，或者和已有项目对比，把没有的删除试试

**Comment by deepkolos** [comment]
我知道了，是微信开发工具版本问题，升级微信开发工具或者把three-platformize-demo-wechat的project.config.json的。。。我忘记了，要不先升级开发工具吧，或者和已有项目对比，把没有的删除试试

**Comment by wujianv5** [comment]
升级了开发工具好了。。。
