### ISSUE TITLE
glTFLoader error working with draco 

### ISSUE THREAD

**Issue by asange** [deepkolos/three-platformize#7]
gltfLoader 导入 draco压缩过glTF文件时， 出现错误：

VM1970 WAService.js:2 ReferenceError: Worker is not defined
    at DRACOLoader.js? [sm]:323
errorReport @ VM1970 WAService.js:2
thirdErrorReport @ VM1970 WAService.js:2
(anonymous) @ VM1970 WAService.js:2
I @ VM1970 WAService.js:2
o @ VM1970 WAService.js:2
(anonymous) @ VM1970 WAService.js:2
value @ VM1970 WAService.js:2
o @ VM1970 WAService.js:2
(anonymous) @ VM1970 WAService.js:2

**Comment by deepkolos** [comment]
目前没适配draco，模型压缩可以使用meshopt代替，可用性和性能的测评比draco好

[【网格压缩测评】MeshQuan、MeshOpt、Draco](https://juejin.cn/post/6931954784018628621)
