### ISSUE TITLE
该如何正确使用这个库？

### ISSUE THREAD

**Issue by wujianv5** [deepkolos/three-platformize#9]
请教一下，如何使用这个库才是正确的方式？

我现在的做法是，按照文档中写的，去link这个库，然后在小程序开发工具中点“构建npm”，然后下面这句
`import WechatPlatform from 'three-platformize/src/WechatPlatform';`
会提示找不到，然后我会在 three-platformize 目录下 build 好 WechatPlatform.js，直接copy到我的工程目录下引用，就可以了。

上面的方法我使用 Three.js 108 版本是可以的，这个版本是微信官方插件使用的版本。
但是当我使用 126 版本的时候，新建renderer会报错
`this.renderer = new THREE.WebGL1Renderer({canvas, antialias: true});`
报错：
`TypeError: Cannot read property 'mark' of undefined`

代码出错的地方是在 WebXRManager 的构造方法中
`
this.setSession = /*#__PURE__*/function () {
			var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(value) {
`

请教一下
1. 使用 three-platformize 的方式是否正确
2. 上面 renderer 的报错可能是什么原因

谢谢！

**Comment by deepkolos** [comment]
推荐使用rollup做二次构建，不使用小程序npm，构建配置可参考

https://github.com/deepkolos/three-platformize-demo-wechat

**Comment by wujianv5** [comment]
找到了一个方法引用 three-platformize。
rollup 编译为 cjs 格式，且把 babel plugin 去掉，即直接修改 rollup.config.three.js，把最后面的 esm 格式更改为 cjs 然后编译。
最后将编译出来的 build/three.module.js 拷贝到项目目录下。

**Comment by deepkolos** [comment]
这样就没tree shaking了
